# prettier-ignore
version: '2.0'
services:
  test:
    image: mheers/nats-auto-server:${NATS_VERSION}
    # build: ./
    environment:
      - OPERATOR_SEED=SOAON2QVZ5L7CMOO5W3PV4F7OCDU7L6AXIO5VA2YWIBTTSLUN64UNOU63M
      - SYS_ACCOUNT_SEED=SAABOFAWXZYMP3LWVULJTFD25YDFA5UEJ4FRIELRRIHQNMSQFDWKLNXS5E
      - ACCOUNT_SEED=SAADBIEN2MTECGRQDK3Y6XHK7PADDSXR6SOCQOM5GFORHLBAX6V6C65OOE
      # - NO_AUTH=true
      - TLS=true
      - WEBSOCKET_PORT=9443
      # - AUTO=off
    volumes:
      - ./autostart.sh:/autostart.sh
      # - ./nats-server.conf:/nats/conf/nats-server.conf
      - ./additional.conf:/nats/conf/additional.conf
      - ./server-cert.pem:/nats/conf/server-cert.pem
      - ./server-key.pem:/nats/conf/server-key.pem
      - ./nats-server.conf.template:/nats/conf/nats-server.conf.template
    # command:
    #   - sleep
    #   - infinity
