# prettier-ignore
version: '2.0'
services:
  test:
    image: mheers/nats-auto-server
    # build: ./
    environment:
      - OPERATOR_SEED=SOACNU5IOX2ORL3J647J2ZL2OLT3NRFHP6DVWM2A7NDT7JPN4YE3POYQOY
      - ACCOUNT_SEED=SAAOKWQVKSHTHFLC4ZDWLIHTEFZURVHT24FB7WXX6PEFHWGBWJ37EWQWGU
    command: 
      - sleep
      - infinity
